<?php
$url = array(
"https://i.imgur.com/KpNOUm8.jpg",
"https://i.imgur.com/pi1vemo.jpg",
"https://i.imgur.com/qQcVvGc.jpg",
"https://i.imgur.com/Igd5YyI.jpg",
"https://i.imgur.com/SzqMC1B.jpg",
"https://i.imgur.com/5SwP8RH.jpg",
"https://i.imgur.com/W89Q5fs.jpg",
"https://i.imgur.com/o6XVsXA.jpg",
"https://i.imgur.com/s05CqGG.jpg",
"https://i.imgur.com/0PNVnvc.jpg",
"https://i.imgur.com/oKLHWIG.jpg",
"https://i.imgur.com/gCx8hGv.jpg",
"https://i.imgur.com/cHuMqZK.jpg",
"https://i.imgur.com/vemlFRu.jpg",
"https://i.imgur.com/1nyFsaE.jpg",
"https://i.imgur.com/F37CPMh.jpg",
"https://i.imgur.com/qwzmWRa.jpg",
"https://i.imgur.com/7w5z1Dr.jpg",
"https://i.imgur.com/6FMuULq.jpg",
"https://i.imgur.com/QP6Oram.jpg",
"https://i.imgur.com/dmB4jDt.jpg",
"https://i.imgur.com/dmB4jDt.jpg",
"https://i.imgur.com/q3BsbUx.jpg",
"https://i.imgur.com/MjjuwlW.jpg",
"https://i.imgur.com/RhtA2c5.jpg",
"https://i.imgur.com/NZZW6Po.jpg",
"https://i.imgur.com/IHr2StU.jpg",
"https://i.imgur.com/TqbTV7N.jpg",
"https://i.imgur.com/86XDAXn.jpg",
"https://i.imgur.com/rHuoP6P.jpg",
"https://i.imgur.com/ErXM66I.jpg",
"https://i.imgur.com/HsfEMAZ.jpg",
"https://i.imgur.com/ONh9qcO.jpg",
"https://i.imgur.com/rNqvp9P.jpg",
"https://i.imgur.com/iHctwJj.jpg",
"https://i.imgur.com/mHcaxi1.jpg",
"https://i.imgur.com/7KQDZsv.jpg",
"https://i.imgur.com/irUKJW1.jpg",
"https://i.imgur.com/pw4UsuA.jpg",
"https://i.imgur.com/IV54Qan.jpg",
"https://i.imgur.com/2gKTrIW.jpg",
"https://i.imgur.com/DQZkUgQ.jpg",
"https://i.imgur.com/4o8Ks3T.jpg",
"https://i.imgur.com/Xa8bqrh.jpg",
"https://i.imgur.com/XvzaNFz.jpg",
"https://i.imgur.com/lBFR155.jpg",
"https://i.imgur.com/61BNiPd.jpg",
"https://i.imgur.com/3GfsWgE.jpg",
"https://i.imgur.com/QOpvO1W.jpg",
"https://i.imgur.com/zZLDxQJ.jpg",
"https://i.imgur.com/bjoDT9L.jpg",
"https://i.imgur.com/kZOD3xH.jpg",
"https://i.imgur.com/7FhbEVk.jpg",
"https://i.imgur.com/Z28E4zb.jpg",
"https://i.imgur.com/sEt92mi.jpg",
"https://i.imgur.com/YjMOZ8y.jpg",
"https://i.imgur.com/cj8HOYy.jpg",
"https://i.imgur.com/y74q7WF.jpg",
"https://i.imgur.com/JwW7qix.jpg",
"https://i.imgur.com/WMPh11u.jpg",
"https://i.imgur.com/AQEIi7m.jpg",
"https://i.imgur.com/ONtEMRx.jpg",
"https://i.imgur.com/47cALyC.jpg",
"https://i.imgur.com/eZeLuJB.jpg",
"https://i.imgur.com/1GyMT4E.jpg",
"https://i.imgur.com/3YXWXTT.jpg",
"https://i.imgur.com/Wk5ZEmp.jpg",
"https://i.imgur.com/kDNv8tW.jpg",
"https://i.imgur.com/NmICyIA.jpg",
"https://i.imgur.com/5jqgcW7.jpg",
"https://i.imgur.com/GHAXZUh.jpg",
"https://i.imgur.com/kwwLAYQ.jpg",
"https://i.imgur.com/ECimtFh.jpg",
"https://i.imgur.com/2f5dcSA.jpg",
"https://i.imgur.com/5kmDekD.jpg",
"https://i.imgur.com/w3Hfquj.jpg",
"https://i.imgur.com/qW1AxsL.jpg",
"https://i.imgur.com/Wzpe9tU.jpg",
"https://i.imgur.com/SxOFY1p.jpg",
"https://i.imgur.com/RxBryf5.jpg",
"https://i.imgur.com/4DkPC5t.jpg",
"https://i.imgur.com/l06HU0J.jpg",
"https://i.imgur.com/Uivl7T4.jpg",
"https://i.imgur.com/tLrPd7r.jpg",
"https://i.imgur.com/RboGKh5.jpg",
"https://i.imgur.com/RboGKh5.jpg",
"https://i.imgur.com/UDf9YNO.jpg",
"https://i.imgur.com/efpTsGV.jpg"
);
$rd = array_rand($url);
$cc = $url [$rd];
$kiss = array(
"data" => $cc,
"author" => "Trần khương",
"success" => "true",
);
$rdimg = json_encode($kiss);

$i = ['\/v\/','\/','L\u00ea C\u00f4ng Quy\u1ec1n'];
$t = ['/v/','/','Trần khương'];
$j = str_replace($i, $t, $rdimg);
echo $j;
